<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUBr7lov\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUBr7lov/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUBr7lov.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUBr7lov\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUBr7lov\App_KernelDevDebugContainer([
    'container.build_hash' => 'UBr7lov',
    'container.build_id' => '7d867d5f',
    'container.build_time' => 1727791646,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUBr7lov');
